version: '3.3'
services:
  rabbit:
    container_name: rabbitmq
    image: "rabbitmq:3-management"
    hostname: "rabbit"
    environment:
      RABBITMQ_ERLANG_COOKIE: "TjMkjx8E8C1jqMtekH7tJeBnfVIX4iW3o7kFfY"
      RABBITMQ_DEFAULT_USER: "rabbitmquser"
      RABBITMQ_DEFAULT_PASS: "rabbitmqpass"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
    labels:
      NAME: "rmq"

# docker-compose up
# docker run -d -p 15672:15672 -p 5672:5672 rmq